### ISSUE TITLE
Refreshing after submission causes a repost.

### ISSUE THREAD

**Issue by LiminalCrab** [cblgh/cerca#1] opened 2022-01-11 18:44 UTC
After submitting a reply to a thread, refreshing the page in the browser will cause the reply to be submitted again.

**Comment by icco** [comment] 2022-01-12 13:30
#10 is a duplicate of this, but has a bit of research into the topic.

**Comment by cblgh** [comment] 2022-01-12 16:28
i think it's fixed in https://github.com/cblgh/cerca/commit/fc3e4e691b6222f41b6d8df2baa87eee2aa4844f :)

**Closed by cblgh** 2022-01-12 16:28 UTC
